# TCL File Generated by Component Editor 23.1
# Sat Jun 15 23:16:37 EEST 2024
# DO NOT MODIFY


# 
# mand_cluster_avalon_mm "Mandelbrot Cluster With Avalon-MM Slave" v1.0
#  2024.06.15.23:16:37
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module mand_cluster_avalon_mm
# 
set_module_property DESCRIPTION ""
set_module_property NAME mand_cluster_avalon_mm
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Mandelbrot Cluster With Avalon-MM Slave"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL mand_cluster_avalon_mm
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file mand_cluster_avalon_mm.vhd VHDL PATH ../ip/mand_avalon_cluster_avalon_mm/mand_cluster_avalon_mm.vhd TOP_LEVEL_FILE
add_fileset_file mandelbrot_core.vhd VHDL PATH ../libs/mand/components/mandelbrot_core/src/mandelbrot_core.vhd
add_fileset_file multiply_block.vhd VHDL PATH ../libs/mand/components/multiply_block/src/multiply_block.vhd
add_fileset_file functions.vhd VHDL PATH ../libs/mand/pkg/functions.vhd


# 
# parameters
# 
add_parameter CORES_COUNT NATURAL 2
set_parameter_property CORES_COUNT DEFAULT_VALUE 2
set_parameter_property CORES_COUNT DISPLAY_NAME CORES_COUNT
set_parameter_property CORES_COUNT TYPE NATURAL
set_parameter_property CORES_COUNT UNITS None
set_parameter_property CORES_COUNT ALLOWED_RANGES 0:2147483647
set_parameter_property CORES_COUNT HDL_PARAMETER true
add_parameter FIXED_SIZE NATURAL 32
set_parameter_property FIXED_SIZE DEFAULT_VALUE 32
set_parameter_property FIXED_SIZE DISPLAY_NAME FIXED_SIZE
set_parameter_property FIXED_SIZE TYPE NATURAL
set_parameter_property FIXED_SIZE UNITS None
set_parameter_property FIXED_SIZE ALLOWED_RANGES 0:2147483647
set_parameter_property FIXED_SIZE HDL_PARAMETER true
add_parameter FIXED_INTEGER_SIZE NATURAL 5
set_parameter_property FIXED_INTEGER_SIZE DEFAULT_VALUE 5
set_parameter_property FIXED_INTEGER_SIZE DISPLAY_NAME FIXED_INTEGER_SIZE
set_parameter_property FIXED_INTEGER_SIZE TYPE NATURAL
set_parameter_property FIXED_INTEGER_SIZE UNITS None
set_parameter_property FIXED_INTEGER_SIZE ALLOWED_RANGES 0:2147483647
set_parameter_property FIXED_INTEGER_SIZE HDL_PARAMETER true
add_parameter AVALON_DATA_WIDTH NATURAL 8
set_parameter_property AVALON_DATA_WIDTH DEFAULT_VALUE 8
set_parameter_property AVALON_DATA_WIDTH DISPLAY_NAME AVALON_DATA_WIDTH
set_parameter_property AVALON_DATA_WIDTH TYPE NATURAL
set_parameter_property AVALON_DATA_WIDTH UNITS None
set_parameter_property AVALON_DATA_WIDTH ALLOWED_RANGES 0:2147483647
set_parameter_property AVALON_DATA_WIDTH HDL_PARAMETER true
add_parameter AVALON_ADDRESS_WIDTH NATURAL 10
set_parameter_property AVALON_ADDRESS_WIDTH DEFAULT_VALUE 10
set_parameter_property AVALON_ADDRESS_WIDTH DISPLAY_NAME AVALON_ADDRESS_WIDTH
set_parameter_property AVALON_ADDRESS_WIDTH TYPE NATURAL
set_parameter_property AVALON_ADDRESS_WIDTH UNITS None
set_parameter_property AVALON_ADDRESS_WIDTH HDL_PARAMETER true
add_parameter FLAG_REG_SIZE NATURAL 124
set_parameter_property FLAG_REG_SIZE DEFAULT_VALUE 124
set_parameter_property FLAG_REG_SIZE DISPLAY_NAME FLAG_REG_SIZE
set_parameter_property FLAG_REG_SIZE TYPE NATURAL
set_parameter_property FLAG_REG_SIZE UNITS None
set_parameter_property FLAG_REG_SIZE ALLOWED_RANGES 0:2147483647
set_parameter_property FLAG_REG_SIZE HDL_PARAMETER true
add_parameter NORMAL_REG_SIZE NATURAL 32
set_parameter_property NORMAL_REG_SIZE DEFAULT_VALUE 32
set_parameter_property NORMAL_REG_SIZE DISPLAY_NAME NORMAL_REG_SIZE
set_parameter_property NORMAL_REG_SIZE TYPE NATURAL
set_parameter_property NORMAL_REG_SIZE UNITS None
set_parameter_property NORMAL_REG_SIZE ALLOWED_RANGES 0:2147483647
set_parameter_property NORMAL_REG_SIZE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 avs_address address Input 10
add_interface_port avalon_slave_0 avs_read read Input 1
add_interface_port avalon_slave_0 avs_write write Input 1
add_interface_port avalon_slave_0 avs_writedata writedata Input "((avalon_data_width-1)) - (0) + 1"
add_interface_port avalon_slave_0 avs_readdata readdata Output "((avalon_data_width-1)) - (0) + 1"
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1

